'use client'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Nav from '@/components/Nav'
import { usePathname } from 'next/navigation'

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app'
// }

export default function RootLayout ({ children }) {
  const path = usePathname()
  return (
    <html lang='en'>
      <body className={` antialiased `}>
      {
            path == '/verifiedTax' || path == '/register' 
            ?
            <div></div>
            :
            <div className="hidden justify-center items-center xl:flex bg-[url('../image/fbg.svg')] bg-cover bg-no-repeat h-screen w-1/2">
                <Nav />
              </div>
          }
        {children}
      </body>
    </html>
  )
}
